### ISSUE TITLE
Missing file "META.stay" referenced in setup.py

### ISSUE THREAD

**Issue by gitclem** [amogorkon/fuzzylogic#1]
In the file setup.py, there is the statement:

`with open("META.stay") as f:`

but there is no file META.stay anywhere in the package code.

**Comment by amogorkon** [comment]
Ohai, welcome! You're the first to try and install my package 🥇 :)
I've been working on the stay module lately so I must've messed up this dependency on my other packages like this one.
I can remove this dependency for you so you can try and install fuzzylogic.

Hey, do you mind me asking what you want to use the package for? I generally just use the functions module in my other projects, so maybe I can help you with your usecase?

**Comment by gitclem** [comment]
> Ohai, welcome! You're the first to try and install my package 🥇 :)
> I've been working on the stay module lately so I must've messed up this dependency on my other packages like this one.
> I can remove this dependency for you so you can try and install fuzzylogic.
> 
> Hey, do you mind me asking what you want to use the package for? I generally just use the functions module in my other projects, so maybe I can help you with your usecase?

I had great success at a previous job with Fuzzy Logic that was created in Ruby, so I'm a big fan of FL.

I think it's a great alternative to when you don't have many labeled training sets (will take too long or cost too much, or the positive cases are rare), can be a domain expert, need a model quickly, and the problem isn't overly complex.

I'm not sure what I will be doing with FL yet.  I like to have FL as a tool in my toolbox.

**Comment by gitclem** [comment]
Works now.  But, the package "stay" needs to be installed first.

So, it would be useful to check to make sure that package is installed.

**Comment by amogorkon** [comment]
Glad to hear that it worked. Please let me know if you need help with anything or have ideas on how to improve (usecases, code design..) the package.
