### ISSUE TITLE
fuzzy - Caro die scheiße will oifach itte

### ISSUE THREAD

**Issue by caro174** [amogorkon/fuzzylogic#16]
```
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 17 15:41:20 2021

@author: carow
"""


from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.functions import R , S, trapezoid
from fuzzylogic.rules import weighted_sum

tempval=20
tanval=0.55

temp=Domain('Temperatur',-30,100)#,res=0.1)
temp.kalt = S(-10,30)
#temp.kalt.plot()
temp.heis = R(30, 70)
#temp.heis.plot()
temp.mittel = ~temp.heis & ~temp.kalt
#temp.mittel.plot()


tan=Domain('tandelta',0,1.3)#,res=0.1)
tan.klein = S(0.1,0.5)
#tan.klein.plot()
tan.gros = R(0.5, 0.9)
#tan.gros.plot()
tan.mittel = ~tan.gros & ~tan.klein
#tan.mittel.plot()

gef=Domain('Gefahrenbewertung',-0.5,1.5)#,res=0.1)
gef.klein = trapezoid(-0.5,0,0,0.5) 
gef.klein.plot()
gef.gros = trapezoid(0.5, 1, 1,1.5)
gef.gros.plot()
gef.mittel = trapezoid(0, 0.5, 0.5,1)
tan.mittel.plot()

"""
gef=Domain('Gefahrenbewertung',-0.5,1.5,res=0.1)
gef.klein = S(0,0.5) 
gef.klein.plot()
gef.gros = R(0.5, 1)
gef.gros.plot()
gef.mittel = ~gef.klein & ~gef.gros
tan.mittel.plot()

gef=Domain('Gefahrenbewertung',0.5,2.5)#,res=0.1)
gef.klein = trapezoid(0.5,1,1,1.5) 
gef.klein.plot()
gef.gros = trapezoid(1.5, 2, 2,2.5)
gef.gros.plot()
gef.mittel = trapezoid(1, 1.5, 1.5,2.5)
tan.mittel.plot()
"""

R1=Rule({(temp.kalt, tan.klein): gef.klein })
R2=Rule({(temp.mittel, tan.klein): gef.klein })
R3=Rule({(temp.heis, tan.klein): gef.klein })
R4=Rule({(temp.kalt, tan.mittel): gef.klein})
R5=Rule({(temp.mittel, tan.mittel): gef.mittel })
R6=Rule({(temp.heis, tan.mittel): gef.gros})
R7=Rule({(temp.kalt, tan.gros): gef.mittel })
R8=Rule({(temp.mittel, tan.gros): gef.gros })
R9=Rule({(temp.heis, tan.gros): gef.gros })


rules = R1 | R2 | R3 | R4 | R5 | R6 | R7 | R8 | R9
#rules = sum([R1, R2, R3, R4, R5, R6, R7, R8, R9])

value = {temp: tempval, tan: tanval}
print(R4(value))
print(R1(value), R2(value), R3(value), R4(value), "klein", R5(value),"mittel", R6(value), R7(value),"mittel", R8(value),"gros", R9(value),"gros")
print( "=>", rules(value))

```

**Comment by amogorkon** [comment]
Das Problem scheint `gef=Domain('Gefahrenbewertung',-0.5,1.5)` zu sein. die default Auflösung von 1 produziert hier über Umwege ein Array [0, 0, 0] was https://numpy.org/doc/stable/reference/generated/numpy.average.html gar nicht mag ("The only constraint on weights is that sum(weights) must not be 0."). Mit einer Auflösung von 0.1 wird zumindest keine Exception mehr geworfen..

**Comment by amogorkon** [comment]
Frage ist wie das [0, 0, 0] zustande kommt.. hmm.

**Comment by amogorkon** [comment]
Ich brauch ne Liste von Eingaben -> erwarteten Ausgaben um daraus einen zuverlässigen Test für die CoG Regeln zu bauen..

**Comment by amogorkon** [comment]
Aha! `Domain("Gefahrenbewertung", -0.5, 1.5)` resultiert in einem `array([-0.5,  0.5,  1.5])` als "Abtastpunkte" für die Funktion `gef.klein = trapezoid(-0.5, 0, 0, 0.5)` (ein degeneriertes Trapez, also eigentlich triangular), wobei -0.5 und 0.5 genau den Eckpunkten des Trapez entspricht und 1.5 weit außerhalb liegt, also damit korrekt [0, 0, 0] ergibt.

**Comment by amogorkon** [comment]
Kleine Anmerkung, wahrscheinlich aber nicht die Lösung für das Problem: Meiner Erfahrung nach sind nicht-überlappende Sets oft problematisch. Bei `gef.klein = trapezoid(-0.5, 0, 0, 0.5);
gef.groß = trapezoid(0.5, 1, 1, 1.5)` z. B. fängt das eine Set genau da an wo das andere aufhört, das heißt, es gibt hier ein "Loch" im Definitionsbereich.

**Comment by caro174** [comment]
in dem Loch liegt dann doch eigentlich die "mittel" Bereich oder?

**Comment by amogorkon** [comment]
Stimmt. 
```gef.klein = trapezoid(-0.5, 0, 0, 0.5)
gef.groß = trapezoid(0.5, 1, 1, 1.5)
gef.mittel = trapezoid(0, 0.5, 0.5, 1)```
War auch nur ne Anmerkung, weil das mal ein ärgerliches Problem war

**Comment by amogorkon** [comment]
Ich hab jetzt mal 
```
    def center_of_gravity(self):
        """Return the center of gravity for this distribution, within the given domain."""
        if self.__center_of_gravity is not None:
            return self.__center_of_gravity

        weights = self.array()
        if sum(weights) == 0:
            return 0
        cog = np.average(np.arange(len(weights)), weights=weights)
        self.__center_of_gravity = cog
        return cog
```
in meinem Code, das umgeht zumindest das np.average Problem für diesen degenerierten Fall..

Wenn man die Auflösung hoch dreht, läuft man in das andere Problem, dass der ausgegebene Wert unintuitiv wird.. ich glaube, da fehlt eine Normalisierung zum Range der Domain *denk*

**Comment by amogorkon** [comment]
Eine Domain Gefahrenbewertung von -0.5 bis 1.5 und einer Auflösung von 0.0001 würde dann mit tempval = 20 und tanval = 0.55 einen Wert von 0.45 liefern, ist das korrekt?

**Comment by caro174** [comment]
Ja!

**Comment by caro174** [comment]
allerdings passiert bei mir dann sowas:

None None None 5000.000000000551 klein 10000.000000001102 mittel None 10000.000000001102 mittel 15000.000000001652 gros None gros

=> 9500.000000001048

**Comment by amogorkon** [comment]
> allerdings passiert bei mir dann sowas:
> 
> None None None 5000.000000000551 klein 10000.000000001102 mittel None 10000.000000001102 mittel 15000.000000001652 gros None gros
> 
> => 9500.000000001048

genau das ist die fehlende Normalisierung, von der ich sprach. Dieses Ergebnis entspricht dem Index eines 20k-elementigen Arrays von -0.5 bis 1.5, also: 
`(1.5-(-0.5)/20000)*9500+(-0.5) = 0.45`

**Comment by amogorkon** [comment]
Probiers mal mit
```
def normalize_to_domain(domain, index):
    return (domain.maximum - domain.minimum) / len(domain.range) * index + domain.minimum
```
und index als die Ausgabe der Regel (in dem Fall 9500)

**Comment by caro174** [comment]
wo soll ich das eintragen? in das classes-Skript oder in meins?^^

**Comment by caro174** [comment]
`R7=Rule({(temp.kalt, tan.gros): gef.mittel })
R8=Rule({(temp.mittel, tan.gros): gef.gros })
R9=Rule({(temp.heis, tan.gros): gef.gros })

def normalize_to_domain(domain, index):
    return (domain.maximum - domain.minimum) / len(domain.range) * index + domain.minimum

R4 = normalize_to_domain(gef, 4)`

**Comment by caro174** [comment]
So hat es nicht funktioniert ^^

**Comment by amogorkon** [comment]
```
R7=Rule({(temp.kalt, tan.gros): gef.mittel })
R8=Rule({(temp.mittel, tan.gros): gef.gros })
R9=Rule({(temp.heis, tan.gros): gef.gros })

def normalize_to_domain(domain, index):
    return (domain.maximum - domain.minimum) / len(domain.range) * index + domain.minimum

R4 = normalize_to_domain(gef, rules(value))
```
eher so

**Comment by amogorkon** [comment]
ah crap

**Comment by amogorkon** [comment]
domain._high, domain._low

**Comment by amogorkon** [comment]
```
R7=Rule({(temp.kalt, tan.gros): gef.mittel })
R8=Rule({(temp.mittel, tan.gros): gef.gros })
R9=Rule({(temp.heis, tan.gros): gef.gros })
...

def normalize_to_domain(domain, index):
    return (domain._high - domain._low) / len(domain.range) * index + domain._low

print("=>", normalize_to_domain(gef, rules(value)))
=> 0.44995250237498596
```

**Comment by amogorkon** [comment]
problem solved ^^

**Comment by amogorkon** [comment]
ist noch nicht so elegant wie es sein könnte, aber zumindest funktioniert es jetzt wie erwartet :)

**Comment by caro174** [comment]
raise AttributeError(f"{name} is not a set or attribute")

AttributeError: maximum is not a set or attribute

**Comment by caro174** [comment]
geht leider immer noch nicht :/

**Comment by amogorkon** [comment]
Ja, du musst die Funktion 
```
def normalize_to_domain(domain, index):
    return (domain._high - domain._low) / len(domain.range) * index + domain._low
```
verwenden, ich hatte domain.maximum im Kopf, aber es war domain._high

**Comment by amogorkon** [comment]
Falls das nicht funktioniert, copy&paste nochmal deinen ganzen Code hier rein :)

**Comment by amogorkon** [comment]
```
from fuzzylogic.classes import Domain, Rule, Set
from fuzzylogic.functions import R, S, trapezoid

temp = Domain("Temperatur", -30, 100, res=0.0001)  # ,res=0.1)
temp.kalt = S(-10, 30)
temp.heiß = R(30, 70)
temp.mittel = ~temp.heiß & ~temp.kalt


tan = Domain("tandelta", 0, 1.3, res=0.0001)  # ,res=0.1)
tan.klein = S(0.1, 0.5)
tan.groß = R(0.5, 0.9)
tan.mittel = ~tan.groß & ~tan.klein

gef = Domain("Gefahrenbewertung", -0.5, 1.5, res=0.0001)  # ,res=0.1)
gef.klein = trapezoid(-0.5, 0, 0, 0.5)
gef.groß = trapezoid(0.5, 1, 1, 1.5)
gef.mittel = trapezoid(0, 0.5, 0.5, 1)

R1 = Rule({(temp.kalt, tan.klein): gef.klein})
R2 = Rule({(temp.mittel, tan.klein): gef.klein})
R3 = Rule({(temp.heiß, tan.klein): gef.klein})
R4 = Rule({(temp.kalt, tan.mittel): gef.klein})
R5 = Rule({(temp.mittel, tan.mittel): gef.mittel})
R6 = Rule({(temp.heiß, tan.mittel): gef.groß})
R7 = Rule({(temp.kalt, tan.groß): gef.mittel})
R8 = Rule({(temp.mittel, tan.groß): gef.groß})
R9 = Rule({(temp.heiß, tan.groß): gef.groß})


rules = R1 | R2 | R3 | R4 | R5 | R6 | R7 | R8 | R9

tempval = 20
tanval = 0.55


def normalize_to_domain(domain, index):
    return (domain._high - domain._low) / len(domain.range) * index + domain._low


value = {temp: tempval, tan: tanval}
print(R4(value))
print(
    R1(value),
    R2(value),
    R3(value),
    R4(value),
    "klein",
    R5(value),
    "mittel",
    R6(value),
    R7(value),
    "mittel",
    R8(value),
    "groß",
    R9(value),
    "groß",
)
print("=>", normalize_to_domain(gef, rules(value)))
```

**Comment by amogorkon** [comment]
Die Normalisierung muss ich noch in den `__call__` von Rule einarbeiten, so dass das standardmäßig gemacht wird

**Comment by caro174** [comment]
funktioniert 👍

**Comment by amogorkon** [comment]
Super! Meld dich, falls ich sonst noch behilflich sein kann :)

**Comment by amogorkon** [comment]
Ich hab die Sachen in den Code selber eingebaut und n neues Release gemacht, falls du es ausprobieren willst (python -m pip install -U fuzzylogic)
