### ISSUE TITLE
module stay required, but not installed during installation

### ISSUE THREAD

**Issue by m-dz** [amogorkon/fuzzylogic#2]
Hi, I've just tried installing your module on Windows 10 with python 3 and unfortunately encountered error mentioned in #1 , might be worth adding `stay` to the `setup.py`.

Error code below:

```
$ pip install fuzzylogic
Collecting fuzzylogic
  Downloading https://files.pythonhosted.org/packages/d4/e7/cba3173e3672a9686a68f52314f8595209cc22d1bc6e963a21cdc560a23e/fuzzylogic-0.1.2.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\md\AppData\Local\Temp\pip-build-rd5iob3u\fuzzylogic\setup.py", line 7, in <module>
        from stay import load
    ModuleNotFoundError: No module named 'stay'
```

**Comment by m-dz** [comment]
Update: it finally worked, but some clean-up might still be needed:

- Two libraries are missing from requirements: `dataclasses` and `stay`
- I had to install `fuzzylogic` via `pip install git+https://github.com/amogorkon/fuzzylogic` (v 0.1.1.post5) as `pip install fuzzylogic` (v 0.1.2.post2) was causing the `FileNotFoundError: [Errno 2] No such file or directory: 'META.stay' error`. There seems to be something wrong with the newer version on pip.

**Comment by Luferov** [comment]
https://github.com/Luferov/FuzzyLogicToolBox
