### ISSUE TITLE
Cannot import name 'load' from 'stay'

### ISSUE THREAD

**Issue by katerss1** [amogorkon/fuzzylogic#3]
**Hi there!**

Thanks for creating this wonderful repository in advance. 
My teacher is referring to your repository as tool for learning and creating Fuzzy Logic. 
I would like to get started with Fuzzy Logic but I am unable to install your package due to errors.

What I have done beforehand is the following:

- `pip3 install dataclasses`
- `pip3 install stay`

But when I try this:
- `pip3 install fuzzylogic`

this error pops up:
```
ImportError: cannot import name 'load' from 'stay'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I have also tried the following as describe in [Issue 2](https://github.com/amogorkon/fuzzylogic/issues/2):
`pip3 install git+https://github.com/amogorkon/fuzzylogic` but with no success.

Is there something I can do to fix this problem?
Is there something wrong with your [Stay package](https://github.com/amogorkon/stay)? When I look for the `load()` function in your Stay package I am unable to find it.

**Comment by amogorkon** [comment]
Hey Stefan!
I'm very surprised and happy to hear that my tinkering even ended up as a study recommendation, that's unexpected! 

About your problem. I changed a few things in stay, yes. Try 

> from stay import Decoder
> load = Decoder()

that should fix things.

**Comment by amogorkon** [comment]
Btw, please do feel free to report more problems or ideas if you come across anything. For my personal stuff, I usually recycle the "functions" module from the fuzzylogic lib, not the whole package, so I kind of lost track of possible improvements.

**Comment by katerss1** [comment]
Your solution worked for me! Thanks a lot.

**Comment by katerss1** [comment]
I will 

> Btw, please do feel free to report more problems or ideas if you come across anything. For my personal stuff, I usually recycle the "functions" module from the fuzzylogic lib, not the whole package, so I kind of lost track of possible improvements.

I will!
